### PR TITLE
Place 'apk install' packages onto separate lines

### PR DESCRIPTION
**Pull request by jayaddison**
Following the [Best practices for writing Dockerfiles](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run), we can make the `apk install` step a little easier to read (especially when changes/diffs occur) by placing each package on a separate line.

### CODE REVIEW

**Comment by jayaddison** [comment]
No functional changes are yet made to the existing code as it stands from a few months ago.  Only formatting modifications are applied to the code in this initial changeset.

There will be follow-up pull requests to this one - each of small size - which apply consistency and safety improvements.

**Comment by jayaddison** [comment]
@talmai @berrnd does this change seem reasonable?  I'd like to clean up this and a few more aspects of the container build process, by opening a few more small PRs like this one.

**Comment by berrnd** [comment]
Sorry, I'm still not maintaining this mainly because I never used Docker so far anywhere...

Would you @jayaddison like to co-maintain grocy-docker? Would be great! :)

**Comment by jayaddison** [comment]
@berrnd No problem!  I'll take some time to consider joining as a co-maintainer.

Ultimately what I'm navigating towards with these small steps is a minimal, horizontally-scalable `grocy` platform which be self-hosted on Kubernetes for use by large numbers of users.

My first goal is to help bring [opencontainer](https://www.opencontainers.org/) compatibility to `grocy-docker` and to apply small cleanups (like this PR) during the process.

Data persistence can be a tricky problem for containerized software and that would be my next area of focus, leading to suggestions affecting the `grocy` architecture and PHP code.

For now I'm comfortable developing changes via a fork.  I'll let you know within the next week or so whether I'd like to co-maintain, and I'd be glad to hear from @talmai about these ideas and teamwork options.

**Comment by jayaddison** [comment]
@berrnd I'd like to accept your offer to become a maintainer for `grocy-docker`.  I'm not sure exactly how long I'll continue that role for.  If & when the project looks relatively stable, I'll drop the privileges again.

**Comment by berrnd** [comment]
Great, thanks for your help. I've sent you an invitation for the grocy GitHub org, afterwards I can give you write permissions for this repository.

If also need access to the image on Docker Hub, I would need your Docker ID to be able to add you there.

**Comment by jayaddison** [comment]
Glad to help - invite accepted.  It'll take me a little while to become familiar with Docker Hub, so I'll let you know once I'm ready to participate there.

**Comment by berrnd** [comment]
Everything done. You should have now "Maintain" permissions for this repository (so feel free to merge your own pull request or do whatever you think it's good for grocy-docker, thanks). :)

**Comment by jayaddison** [comment]
> Everything done. You should have now write permissions for this repository (so feel free to merge your own pull request or do whatever you think it's good for grocy-docker, thanks). :)

All seems to be working great - I've been keeping busy with it :)

Although it'll take me a little while to properly test and release updated versions of `docker-grocy`, I'm now set up on Docker Hub -- my ID there is the same as my GitHub username.

**Comment by berrnd** [comment]
I added you to the org and repo on Docker Hub with full permissions.

**Pull request merged**
