### PR TITLE
Release v3.3.0-0

### PR DESCRIPTION
**Pull request by manheraz**
Hi!

The Docker images are not up to date, so I'd like to help.

Before changing anything, I compared the changes between tags v3.2.0-0 and v3.2.0-1 to be sure which files should be modified and made the required changes to use Grocy 3.3.0 and the Alpine Docker image 3.15.4.

With these changes, the images build and run without problems on my laptop.

I'm no Docker expert, so please, check these changes before accepting them.

Thank you in advance for Grocy and these Docker images!

### CODE REVIEW

**Comment by jayaddison** [comment]
(delayed reply, I've been away from computers for a while) Thanks @manheraz - this looks great!  After you run the images locally, are you able to access the grocy server instance locally and login using the default credentials?

**Comment by manheraz** [comment]
> (delayed reply, I've been away from computers for a while) Thanks @manheraz - this looks great! After you run the images locally, are you able to access the grocy server instance locally and login using the default credentials?

No worries, @jayaddison!

Yes, tested with:

    sudo GROCY_IMAGE_TAG=v3.3.0-0 docker-compose up

Logged in with the default admin credentials without problems.

Should I test anything else?

**Comment by jayaddison** [comment]
Brilliant, thanks @manheraz.  Nope, there isn't yet a formal testing process for these images - I usually perform a login and do a quick browse through a bunch of the application's pages to ensure that there aren't any obvious stacktraces / errors that appear.  Not hugely scientific, though, and automated tests before release would be nice at some point.

For what it's worth: my sense at the moment is that the most likely thing to break during an upgrade would be incompatibilities between the application and the [PHP8 dependencies](https://github.com/grocy/grocy-docker/blob/78f4ce712a0a58e213905ad6a1eb97972f660c47/Dockerfile-grocy-backend#L28-L43) as the former evolves.

**Comment by jayaddison** [comment]
I tested this locally too, and have created [release v3.3.0-0 on GitHub](https://github.com/grocy/grocy-docker/releases/tag/v3.3.0-0) (which has [automatically built and pushed](https://github.com/grocy/grocy-docker/runs/6277907270?check_suite_focus=true) the corresponding [`frontend` and `backend` multi-architecture container images to Docker Hub](https://hub.docker.com/u/grocy)).

**Pull request merged**
